
import {
    PetIcon,
    PoolIcon,
    WifiIcon,
    OutdoorIcon,
    BedIcon,
    AcIcon,
    ParkingIcon,
    BbqIcon,
    DryerIcon,
    WorkIcon,
    ViewIcon,
    CoffeeIcon,
    SecurityIcon,
    FanIcon,
    KitchenIcon,
    GymIcon,
    JacuzziIcon,
    CajaFuerteIcon,
} from '../index'

export const iconMap = {
    pet: PetIcon,
    pool: PoolIcon,
    wifi: WifiIcon,
    outdoor: OutdoorIcon,
    bed: BedIcon,
    ac: AcIcon,
    parking: ParkingIcon,
    bbq: BbqIcon,
    dryer: DryerIcon,
    work: WorkIcon,
    view: ViewIcon,
    coffee: CoffeeIcon,
    security: SecurityIcon,
    fan: FanIcon,
    kitchen: KitchenIcon,
    gym: GymIcon,
    jacuzzi: JacuzziIcon,
    cajaFuerte: CajaFuerteIcon,
}
